#pragma once
#include <cstdint>

namespace XRechnungUtils {
    // Codes as defined in UNTDID 4461
    // https://www.xrepository.de/details/urn:xoev-de:xrechnung:codeliste:untdid.4461_3
    enum class PaymentMeanCode : uint16_t {
        Instrument_not_defined = 1,
        // Not defined legally enforceable agreement between two or more parties (expressing a contractual right or a right to the payment of money).
        Automated_clearing_house_credit,// A credit transaction made through the automated clearing house system.
        Automated_clearing_house_debit, // A debit transaction made through the automated clearing house system.
        ACH_demand_debit_reversal,      // A request to reverse an ACH debit transaction to a demand deposit account.
        ACH_demand_credit_reversal,
        ACH_demand_credit,
        ACH_demand_debit,
        Hold,
        National_or_regional_clearing,
        Cash,
        ACH_savings_credit_reversal,
        ACH_savings_debit_reversal,
        ACH_savings_credit,
        ACH_savings_debit,
        Bookentry_credit,
        Bookentry_debit,
        ACH_demand_cash_CCD_credit,
        ACH_demand_cash_CCD_debit,
        ACH_demand_CTP_credit,
        Cheque,
        Bankers_draft,
        Certified_Bankers_draft,
        Bank_cheque,
        Bill_of_exchange_awaiting_acceptance,
        Certified_cheque,
        Local_cheque,
        ACH_demand_CTP_debit,
        ACH_demand_CTX_credit,
        ACH_demand_CTX_debit,
        Credit_transfer,
        Debit_transfer,
        ACH_demand_cash_CCD_plus_credit,
        ACH_demand_cash_CCD_plus_debit,
        ACH_PPD_deposit,
        ACH_savings_CCD_credit,
        ACH_savings_CCD_debit,
        ACH_savings_CTP_credit,
        ACH_savings_CTP_debit,
        ACH_savings_CTX_credit,
        ACH_savings_CTX_debit,
        ACH_savings_CCD_plus_credit,
        Payment_to_bank_account,
        ACH_savings_CCD_plus_debit,
        Accepted_bill_of_exchange,
        Referenced_home_banking_credit_transfer,
        Interbank_debit_transfer,
        Home_banking_debit_transfer,
        Bank_card,
        Direct_debit,
        Payment_by_postgiro,
        FR_CFONB_Option_A,
        Urgent_commercial_payment,
        Urgent_Treasury_Payment,
        Credit_card,
        Debit_card,
        Bankgiro,
        Standing_agreement,
        SEPA_credit_transfer,
        SEPA_direct_debit,
        Promissory_note,
        Promissory_note_signed_by_debtor,
        Promissory_note_signed_by_debtor_endorsed_by_bank,
        Promissory_note_signed_by_debtor_endorsed_by_third_party,
        Promissory_note_signed_by_bank,
        Promissory_note_signed_by_bank_and_endorsed_by_other_bank,
        Promissory_note_signed_by_third_party,
        Promissory_note_signed_by_third_party_endorsed_by_bank,
        Online_payment_service,
        Transfer_Advice,
        Bill_drawn_by_creditor_on_debtor,
        Bill_drawn_by_creditor_on_bank,
        Bill_drawn_by_creditor_endorsed_by_other_bank,
        Bill_drawn_by_creditor_endorsed_by_third_party,
        Bill_drawn_by_creditor_on_third_party,
        Bill_drawn_by_creditor_on_third_party_accepted_and_endorsed_by_bank,
        Not_transferable_banker_draft = 91,
        Not_transferable_local_cheque,
        Reference_giro,
        Urgent_giro,
        Free_format_giro,
        Requested_method_for_payment_was_not_used,
        Clearing_between_partners,
        Mutually_defined = 999
    };
}// namespace XRechnungUtils
